{
  "hash": "2cf6ccaaaff6bfd6547053b838c1a523",
  "result": {
    "markdown": "---\ntitle: \"Notes on A/B testing\"\nauthor: \"LC\"\ndate: \"2023-10-06\"\nimage: \"magkaki.jpg\"\nexecute:\n  echo: true\n---\n\n\n\n\n\n## The purpose of A/B testing\n\n**A/B test is used to decide which of two versions of a product works better** - e.g. which one of version A or B of a website landing page results in more subscriptions.\n\nThe stats underneath are usually very simple - in the basic case **a two independent samples t-test or chi-square test**.\n\nImportantly, **the actual testing should be preceded by a power analysis** to appropriately design the experiment: undetected false positives and negatives can result in a considerable waste of time and money. A power analysis will help to limit the chance of either of them (and can be swiftly carried out with in a few lines or R code, as we will see below).\n\nIf one of the two versions turns out to be significantly better than the other, it is still worth paying attention to the **confidence intervals** around the point estimate of the difference between A and B, as this informs us about the _range_ of the outcome we can expect after having implemented the chosen version.\n\n\n## Case study\nYou own a cafeteria where people come mostly to enjoy their cappuccino while chatting together. However you realize that the number of people who use the cafeteria as their office is increasing, and you want to attract these digital nomads to your cafeteria. \n\nTo this aim, you are thinking to replace the main image appearing on Google Maps when people look for a cafeteria in your neighbourhood - from an image A showing two friends chatting over a coffee, to an image B depicting a cafeteria table transformed into a co-working space.\n\nTo understand whether this is a good idea, you implement both versions and measure how many of the users who click on your cafeteria will then click on the button to ask directions to your place.\n\n![](imgs/AB_cafeterias.png)\n\nThe point is to estimate whether the new image will draw more users to click on the button for directions to your cafeteria.\n\nThis can be tested using an A/B test.\n\n\n## Power analysis\nThe data onto which the test is run are usually proportion of conversion - e.g. to subscription or purchase. The absolute difference between them however will tell us little about the probability that that difference has been achieved by chance (i.e. null hypothesis). \n\nIn order to decide whether the difference in conversion is worth exploring, it is important to first decide on a few items:\n\n- **(Up)lift** or _effect size_ : what change in the proportion of conversion I am expecting? Or, from a business-oriented perspective: what is the increase in conversion which will make the change financially viable and/or profitable? For instance, if the conversion rate increases 5%, is this enough to justify the expenditure needed to run the test? \n\n- **Significance level**, or _alpha_ : what is the risk I want to accept to detect a difference which is actually due to chance (Type I error)?  Usually alpha is set to 0.05 or 0.01.\n\n- **Power** : what is the risk I want to accept _not_ to find an actual difference (beta)? Power is 1-beta, and it is usually set at 0.8. This denotes the probability of finding an effect which is actually present, rather than due to chance.\n\n- **Sample size** : this is the amount of data points I need to have in order to detect a significant and actual difference - of the expected size - given the chosen significance level and power. In practice, this means how much time do I need to wait to know whether A is more effective than B or _vice versa_. Note that bigger differences require smaller samples (i.e. less time), however this might lead to _failure to detect_ a difference smaller than the expected. \n\nProbably the most important information here is the fact that these four elements are all linked to each other: changing one will affect the others. \n\n![](imgs/power.png)\n\nBalancing these four elements in order to plan an effective A/B experiment is the purpose of power analysis. \n\nFor instance, let's say that each day 200 people click on the image of your cafeteria every day. Out of these, 30 people (15%) \"convert\" to asking directions to reach your cafeteria. By changing the image in google maps, you hope to convince 40% more people to ask for directions (i.e. 42 people, or 21%). \n\nIf we keep the sigificance level and power at 0.01 and 0.8 respectively, for how many days should you run the test to assess the efficacy of either options in attracting people to your cafeteria?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclickers_per_day = 200\npA = 30/clickers_per_day\nuplift = 0.4\n\npB = pA * (1 + uplift)\n\npw <- power.prop.test(p1=pA, p2=pB, power=0.8, alternative='two.sided', sig.level=0.01)\npw\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n     Two-sample comparison of proportions power calculation \n\n              n = 956.2356\n             p1 = 0.15\n             p2 = 0.21\n      sig.level = 0.01\n          power = 0.8\n    alternative = two.sided\n\nNOTE: n is number in *each* group\n```\n:::\n\n```{.r .cell-code}\nNdays_runtime <- pw$n / 200\ncat(\"Experiment runtime:\", Ndays_runtime * 2,\"days\") # the computed sample size is for *each condition!*\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nExperiment runtime: 9.562356 days\n```\n:::\n:::\n\n\nThis is great news. If a 40% uplift is expected/desired, it would take about 10 days to run the test and decide which version of the cafeteria photo to use.\n\nAt the same time, this will prevent us to detect an uplift < 40%. Detecting a smaller difference would require a larger sample, but might still be interesting.\n\nLet's see how many participants would be required to detect an A/B effect of different sizes - with a power of 0.8 and a significance level of 0.01.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npower_range <- function(pA, uplift) {\n pB = pA * (1+uplift)\n pw <- power.prop.test(p1=pA, p2=pB, power=0.8, alternative='two.sided', sig.level=0.01)\n return(pw$n)\n}\n\nuplift_list <- seq(0.1,0.5,0.05)\n\nsample_size <- uplift_list %>% map_dbl(~ power_range(pA, .x)) %>% round\n\n# cbind(uplift_list, sample_size)\n\nbp <- barplot(sample_size, names.arg = uplift_list, ylim = c(0, max(sample_size) + 1000))\ntext(bp, sample_size, labels = sample_size, pos = 3, cex = 0.8, col = \"black\")\n```\n\n::: {.cell-output-display}\n![](AB_notes_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nAfter considering these alternative uplifts, you decide that an uplift of 35% in conversions would still be interesting/profitable for your cafeteria, and it would take only a few days more wrt to the initial 40% uplift expectations (1229 * 2 / 200 = less than two weeks). You therefore decide to to run the experiment for two weeks.\n\n\n\n## Hypothesis testing \n\nAfter two weeks, you finally have your data, and can run the actual test. For simplicity, let's calculate the total number of visitors/conversions by multiplying the respective average value times 14 (days).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNdays_runtime = 14\n\nN_A = 190\nn_conv_A = 32\n\nN_B = 185\nn_conv_B = 38\n\ndf <- tibble(\n photo = c(\"B\",\"A\"),\n n_conversions = c(n_conv_B,n_conv_A) * Ndays_runtime,\n N_visitors = c(N_B, N_A) * Ndays_runtime\n) %>% \n mutate(conversion_rate = (n_conversions / N_visitors) %>% round(4))\n\ndf %>% print()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 4\n  photo n_conversions N_visitors conversion_rate\n  <chr>         <dbl>      <dbl>           <dbl>\n1 B               532       2590           0.205\n2 A               448       2660           0.168\n```\n:::\n:::\n\n\n\nThe main idea is that we want to assess whether the two proportions come from the same binomial distribution. There are two ways to do this:\n\n- z test from proportions - CLT-based normality approximation of the binomial distribution\n- chi-square test\n\n\n_If_ we had continous data (e.g. revenues for version A or B), we would just use a Student's T test (or Welch test). For the case of equal variances, this amount to:\n\n$$T_{dof} = \\frac{ \\bar{x}_A - \\bar{x}_B}{\\sqrt{\\frac{s^2_A}{n_A} + \\frac{s^2_B}{n_B}}}$$\n\nwhere $SD_{pooled} = \\sqrt{\\frac{s^2_A}{n_A} + \\frac{s^2_B}{n_B}}$ is the pooled standard deviation of the two samples.\n\nIn the case of proportions we refer to the binomial distribution, where the mean (expected value) is $n \\cdot p$ and the variance is $n \\cdot p \\cdot (1-p)$. For sufficiently large samples (e.g. > 1000), we can approximate a binomial distribution with a gaussian having parameters:\n\n$$\\mu = p, \\sigma = \\sqrt{\\frac{p(1-p)}{n}}$$\nThis allows us to formulate a test for the difference between the two proportions in a similar way to the t test:\n\n$$z = \\frac{p_B - p_A}{\\sqrt{SE_A^2 + SE_B^2}}$$\nwhere $SE_A$ is the standard error for A (and analogously for B)\n\n$$SE_A = \\sqrt{\\frac{p_A(1-p_A)}{N_A}}$$\nFinally, we compare the obtained Z with the critical value for the chosen significance level.\n\nLet's implement this:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnconv_B <- df$n_conversions[1]\nnconv_A <- df$n_conversions[2]\n\nN_B <- df$N_visitors[1]\nN_A <- df$N_visitors[2]\n\npA = nconv_A / N_A\npB = nconv_B / N_B\n\nSE_B <- sqrt(pB * (1-pB) / N_B)\nSE_A <- sqrt(pA * (1-pA) / N_A)\n\nSE_diff <- sqrt(SE_B^2 + SE_A^2)\n\nz <- (pB - pA)/SE_diff\n\n# two-tails test\npval <- 2 * (1 - pnorm(abs(z)) )\nprint(pval)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.000584267\n```\n:::\n:::\n\n\nA quick graphical display of the comparison, together with all the elements of the calculations, can be obtained using the [AB Testguide website](https://abtestguide.com/calc/)\n\n![](imgs/abtestguide.png)\n\n\nAlternatively, we can use the Pearson chi-square test, to test whether the two distributions - sampled in our pA and pB observations - are the same\n\n$$\\chi^2 = \\sum{\\frac{(O_i - E_i)^2}{E_i}}$$\n\nIn this case we can either use the `prop.test()` function, or the `chisq.test()` function.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nABresult <- prop.test(df$n_conversions, df$N_visitors, correct = F, conf.level = 0.95)\nprint(ABresult)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t2-sample test for equality of proportions without continuity correction\n\ndata:  df$n_conversions out of df$N_visitors\nX-squared = 11.823, df = 1, p-value = 0.0005851\nalternative hypothesis: two.sided\n95 percent confidence interval:\n 0.01590500 0.05806371\nsample estimates:\n   prop 1    prop 2 \n0.2054054 0.1684211 \n```\n:::\n:::\n\n\nIf we want to use the chi-square test function directly, we need to reshape our observation into a contingency table.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontingency_table <- matrix(c(n_conv_B, n_conv_A, N_B - n_conv_B, N_A - n_conv_A), ncol = 2)\ncolnames(contingency_table) <- c(\"YES_Conv\", \"No_Conv\")\nrownames(contingency_table) <- c(\"B\", \"A\")\n\ncontingency_table <- contingency_table * Ndays_runtime\n\nchisq.test(contingency_table, correct = F)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's Chi-squared test\n\ndata:  contingency_table\nX-squared = 9.7459, df = 1, p-value = 0.001797\n```\n:::\n:::\n\n\nThe final results are of course exactly the same, and they are (as expected) comparable to those obtained using the normal approximation of the binomial distribution.\n\n<br>\n\n## Insights from the analysis\n\nIt appears that we can be reasonably confident that implementing option B - the photo of the cafeteria as a workplace - will increase the conversion rate, and therefore our profit.\n\nBut there are more interesting information we can gather from our analysis:\n\n1. **The observed conversion rate for the baseline variant (photo of cafeteria as a meeting place) matches our expectations**. Of course, this happened here because we actually created the data _ad hoc_, but the point to retain is that it is important to check whether our initial expectation about the baseline is met by the observation. \n\n2. **The efficacy of the new photo is smaller than expected**. We were expecting to increase the conversion rate by 35-40%. As a matter of fact, the result from the experiment is that the new picture increases conversion \"only\" by 25% with respect to the baseline. We must therefore evaluate whether this option is still interesting for our business\n\n3. We said that from the results we can be _reasonably confident_ that implementing option B will increase our profits 25% with respect to the actual conversion rate. We can attach a quantitative meaning to this _confidence_, namely by looking at the confidence intervals for this result. \n\n\n## Confidence interval\n\nConfidence intervals (CI) are used to estimate the range of the true (but unknown) value of our parameter of interest from our sampling distribution, with a given confidence level (e.g. 95%).\n\n$$CI = [\\hat p_{Diff} + z_{CL} \\cdot SE_{Diff}; \\hat p_{Diff} - z_{CL} \\cdot SE_{Diff}; ]$$\nWhere:\n\n- $\\hat p_{Diff} = \\hat p_B - \\hat p_A$, that is the difference between the two estimates of conversion rate\n- $z_{CL}$ is the probability associated with our confidence level, e.g. 95%\n- $SE_{Diff}$ is the standard error of the difference between the two proportions, as calculated above\n\nIt is the range in which the difference of the conversion rates would be found if the experiment would be repeated many times.\n\nThe CI can be used for inference, alternatively to the null-hypothesis testing approach. Specifically, if the CI _includes_ 0 (or another value that would make the difference between the two conversion rates not interesting), then we can conclude that there is no significant difference in the efficacy of A or B in terms of conversion rates.\n\nIn our case we can calculate the CI as follows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# for a 95% confidence level\nalpha = 0.05\nz_CL <- qnorm(1-(alpha/2))\n\n# Margin of error\nMOE <- z_CL * SE_diff\n\nCI_low  <- (pB - pA) - MOE\nCI_high <- (pB - pA) + MOE\n\ncat(\"95% CI around the difference between pB and PA: [\",CI_low,CI_high,\"]\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n95% CI around the difference between pB and PA: [ 0.015905 0.05806371 ]\n```\n:::\n:::\n\n\nAs expected, this CI does _not_ contain 0, therefore we reject the null hypothesis of no difference between the two conversion rates.\n\nImportantly, the CI can also be used to compare what we expect in the future - based on our experiment - with what we will actually obtain.  \n\nFor instance, one month after we implement photo B (cafeteria as a shared workplace), we might get a 19% increase in conversion rates, rather than the expected 20.5%. While this might disappoint us, it is indeed within the range described by our confidence interval.\n\nIn fact, our CI around the difference in coversion rates (3.7%) ranges between 1.59% and 5.81%. This means that while our point estimate for the conversion rates is 20.54%, based on our CI we can expect is to range from 18.43% (pA + CI_low) to 22.65% (pA + CI_high).\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n## Links\n[Kelly Wortham's Sample Size Calculation - Myth Buster Edition](https://www.searchdiscovery.com/blog/sample-size-calculation-myth-buster-edition/) and the associated [calculator app](https://www.searchdiscovery.com/how-we-help/services/optimization/sample-size-calculator/)\n\n[AB Testguide calculator](https://abtestguide.com/calc/). Scroll to the bottom of the page for some technical articles.\n\n[Georgiev Intervals and p-values for percent change](https://blog.analytics-toolkit.com/2018/confidence-intervals-p-values-percent-change-relative-difference/)\n\n[MLwiki binomial proportion tests](http://mlwiki.org/index.php/Binomial_Proportion_Tests)\n\n[MLwiki binomial proportion confidence intervals](http://mlwiki.org/index.php/Binomial_Proportion_Confidence_Intervals)\n\n[Confidence intervals in A/B testing results](https://www.linkedin.com/pulse/confidence-intervals-ab-testing-results-surbhi-jain/)\n\n[HBR refresher on A/B testing](https://hbr.org/2017/06/a-refresher-on-ab-testing)\n\n[Khan on CI for the difference between proportions](https://www.khanacademy.org/math/ap-statistics/xfb5d8e68:inference-categorical-proportions/two-sample-z-interval-proportions/v/confidence-intervals-for-the-difference-between-two-proportions)\n\n",
    "supporting": [
      "AB_notes_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}