<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.280">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="LC">
<meta name="dcterms.date" content="2023-10-06">

<title>LC - Notes on A/B testing</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">LC</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html">
 <span class="menu-text">about</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html">
 <span class="menu-text">blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../showcase.html">
 <span class="menu-text">showcase</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-purpose-of-ab-testing" id="toc-the-purpose-of-ab-testing" class="nav-link active" data-scroll-target="#the-purpose-of-ab-testing">The purpose of A/B testing</a></li>
  <li><a href="#case-study" id="toc-case-study" class="nav-link" data-scroll-target="#case-study">Case study</a></li>
  <li><a href="#power-analysis" id="toc-power-analysis" class="nav-link" data-scroll-target="#power-analysis">Power analysis</a></li>
  <li><a href="#hypothesis-testing" id="toc-hypothesis-testing" class="nav-link" data-scroll-target="#hypothesis-testing">Hypothesis testing</a></li>
  <li><a href="#insights-from-the-analysis" id="toc-insights-from-the-analysis" class="nav-link" data-scroll-target="#insights-from-the-analysis">Insights from the analysis</a></li>
  <li><a href="#confidence-interval" id="toc-confidence-interval" class="nav-link" data-scroll-target="#confidence-interval">Confidence interval</a></li>
  <li><a href="#links" id="toc-links" class="nav-link" data-scroll-target="#links">Links</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Notes on A/B testing</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>LC </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 6, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="the-purpose-of-ab-testing" class="level2">
<h2 class="anchored" data-anchor-id="the-purpose-of-ab-testing">The purpose of A/B testing</h2>
<p><strong>A/B test is used to decide which of two versions of a product works better</strong> - e.g.&nbsp;which one of version A or B of a website landing page results in more subscriptions.</p>
<p>The stats underneath are usually very simple - in the basic case <strong>a two independent samples t-test or chi-square test</strong>.</p>
<p>Importantly, <strong>the actual testing should be preceded by a power analysis</strong> to appropriately design the experiment: undetected false positives and negatives can result in a considerable waste of time and money. A power analysis will help to limit the chance of either of them (and can be swiftly carried out with in a few lines or R code, as we will see below).</p>
<p>If one of the two versions turns out to be significantly better than the other, it is still worth paying attention to the <strong>confidence intervals</strong> around the point estimate of the difference between A and B, as this informs us about the <em>range</em> of the outcome we can expect after having implemented the chosen version.</p>
</section>
<section id="case-study" class="level2">
<h2 class="anchored" data-anchor-id="case-study">Case study</h2>
<p>You own a cafeteria where people come mostly to enjoy their cappuccino while chatting together. However you realize that the number of people who use the cafeteria as their office is increasing, and you want to attract these digital nomads to your cafeteria.</p>
<p>To this aim, you are thinking to replace the main image appearing on Google Maps when people look for a cafeteria in your neighbourhood - from an image A showing two friends chatting over a coffee, to an image B depicting a cafeteria table transformed into a co-working space.</p>
<p>To understand whether this is a good idea, you implement both versions and measure how many of the users who click on your cafeteria will then click on the button to ask directions to your place.</p>
<p><img src="imgs/AB_cafeterias.png" class="img-fluid"></p>
<p>The point is to estimate whether the new image will draw more users to click on the button for directions to your cafeteria.</p>
<p>This can be tested using an A/B test.</p>
</section>
<section id="power-analysis" class="level2">
<h2 class="anchored" data-anchor-id="power-analysis">Power analysis</h2>
<p>The data onto which the test is run are usually proportion of conversion - e.g.&nbsp;to subscription or purchase. The absolute difference between them however will tell us little about the probability that that difference has been achieved by chance (i.e.&nbsp;null hypothesis).</p>
<p>In order to decide whether the difference in conversion is worth exploring, it is important to first decide on a few items:</p>
<ul>
<li><p><strong>(Up)lift</strong> or <em>effect size</em> : what change in the proportion of conversion I am expecting? Or, from a business-oriented perspective: what is the increase in conversion which will make the change financially viable and/or profitable? For instance, if the conversion rate increases 5%, is this enough to justify the expenditure needed to run the test?</p></li>
<li><p><strong>Significance level</strong>, or <em>alpha</em> : what is the risk I want to accept to detect a difference which is actually due to chance (Type I error)? Usually alpha is set to 0.05 or 0.01.</p></li>
<li><p><strong>Power</strong> : what is the risk I want to accept <em>not</em> to find an actual difference (beta)? Power is 1-beta, and it is usually set at 0.8. This denotes the probability of finding an effect which is actually present, rather than due to chance.</p></li>
<li><p><strong>Sample size</strong> : this is the amount of data points I need to have in order to detect a significant and actual difference - of the expected size - given the chosen significance level and power. In practice, this means how much time do I need to wait to know whether A is more effective than B or <em>vice versa</em>. Note that bigger differences require smaller samples (i.e.&nbsp;less time), however this might lead to <em>failure to detect</em> a difference smaller than the expected.</p></li>
</ul>
<p>Probably the most important information here is the fact that these four elements are all linked to each other: changing one will affect the others.</p>
<p><img src="imgs/power.png" class="img-fluid"></p>
<p>Balancing these four elements in order to plan an effective A/B experiment is the purpose of power analysis.</p>
<p>For instance, let’s say that each day 200 people click on the image of your cafeteria every day. Out of these, 30 people (15%) “convert” to asking directions to reach your cafeteria. By changing the image in google maps, you hope to convince 40% more people to ask for directions (i.e.&nbsp;42 people, or 21%).</p>
<p>If we keep the sigificance level and power at 0.01 and 0.8 respectively, for how many days should you run the test to assess the efficacy of either options in attracting people to your cafeteria?</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>clickers_per_day <span class="ot">=</span> <span class="dv">200</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>pA <span class="ot">=</span> <span class="dv">30</span><span class="sc">/</span>clickers_per_day</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>uplift <span class="ot">=</span> <span class="fl">0.4</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>pB <span class="ot">=</span> pA <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">+</span> uplift)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>pw <span class="ot">&lt;-</span> <span class="fu">power.prop.test</span>(<span class="at">p1=</span>pA, <span class="at">p2=</span>pB, <span class="at">power=</span><span class="fl">0.8</span>, <span class="at">alternative=</span><span class="st">'two.sided'</span>, <span class="at">sig.level=</span><span class="fl">0.01</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>pw</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
     Two-sample comparison of proportions power calculation 

              n = 956.2356
             p1 = 0.15
             p2 = 0.21
      sig.level = 0.01
          power = 0.8
    alternative = two.sided

NOTE: n is number in *each* group</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>Ndays_runtime <span class="ot">&lt;-</span> pw<span class="sc">$</span>n <span class="sc">/</span> <span class="dv">200</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Experiment runtime:"</span>, Ndays_runtime <span class="sc">*</span> <span class="dv">2</span>,<span class="st">"days"</span>) <span class="co"># the computed sample size is for *each condition!*</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Experiment runtime: 9.562356 days</code></pre>
</div>
</div>
<p>This is great news. If a 40% uplift is expected/desired, it would take about 10 days to run the test and decide which version of the cafeteria photo to use.</p>
<p>At the same time, this will prevent us to detect an uplift &lt; 40%. Detecting a smaller difference would require a larger sample, but might still be interesting.</p>
<p>Let’s see how many participants would be required to detect an A/B effect of different sizes - with a power of 0.8 and a significance level of 0.01.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>power_range <span class="ot">&lt;-</span> <span class="cf">function</span>(pA, uplift) {</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a> pB <span class="ot">=</span> pA <span class="sc">*</span> (<span class="dv">1</span><span class="sc">+</span>uplift)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a> pw <span class="ot">&lt;-</span> <span class="fu">power.prop.test</span>(<span class="at">p1=</span>pA, <span class="at">p2=</span>pB, <span class="at">power=</span><span class="fl">0.8</span>, <span class="at">alternative=</span><span class="st">'two.sided'</span>, <span class="at">sig.level=</span><span class="fl">0.01</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a> <span class="fu">return</span>(pw<span class="sc">$</span>n)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>uplift_list <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">0.1</span>,<span class="fl">0.5</span>,<span class="fl">0.05</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>sample_size <span class="ot">&lt;-</span> uplift_list <span class="sc">%&gt;%</span> <span class="fu">map_dbl</span>(<span class="sc">~</span> <span class="fu">power_range</span>(pA, .x)) <span class="sc">%&gt;%</span> round</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="co"># cbind(uplift_list, sample_size)</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>bp <span class="ot">&lt;-</span> <span class="fu">barplot</span>(sample_size, <span class="at">names.arg =</span> uplift_list, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">max</span>(sample_size) <span class="sc">+</span> <span class="dv">1000</span>))</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(bp, sample_size, <span class="at">labels =</span> sample_size, <span class="at">pos =</span> <span class="dv">3</span>, <span class="at">cex =</span> <span class="fl">0.8</span>, <span class="at">col =</span> <span class="st">"black"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="AB_notes_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>After considering these alternative uplifts, you decide that an uplift of 35% in conversions would still be interesting/profitable for your cafeteria, and it would take only a few days more wrt to the initial 40% uplift expectations (1229 * 2 / 200 = less than two weeks). You therefore decide to to run the experiment for two weeks.</p>
</section>
<section id="hypothesis-testing" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-testing">Hypothesis testing</h2>
<p>After two weeks, you finally have your data, and can run the actual test. For simplicity, let’s calculate the total number of visitors/conversions by multiplying the respective average value times 14 (days).</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>Ndays_runtime <span class="ot">=</span> <span class="dv">14</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>N_A <span class="ot">=</span> <span class="dv">190</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>n_conv_A <span class="ot">=</span> <span class="dv">32</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>N_B <span class="ot">=</span> <span class="dv">185</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>n_conv_B <span class="ot">=</span> <span class="dv">38</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a> <span class="at">photo =</span> <span class="fu">c</span>(<span class="st">"B"</span>,<span class="st">"A"</span>),</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a> <span class="at">n_conversions =</span> <span class="fu">c</span>(n_conv_B,n_conv_A) <span class="sc">*</span> Ndays_runtime,</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a> <span class="at">N_visitors =</span> <span class="fu">c</span>(N_B, N_A) <span class="sc">*</span> Ndays_runtime</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span> </span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a> <span class="fu">mutate</span>(<span class="at">conversion_rate =</span> (n_conversions <span class="sc">/</span> N_visitors) <span class="sc">%&gt;%</span> <span class="fu">round</span>(<span class="dv">4</span>))</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  photo n_conversions N_visitors conversion_rate
  &lt;chr&gt;         &lt;dbl&gt;      &lt;dbl&gt;           &lt;dbl&gt;
1 B               532       2590           0.205
2 A               448       2660           0.168</code></pre>
</div>
</div>
<p>The main idea is that we want to assess whether the two proportions come from the same binomial distribution. There are two ways to do this:</p>
<ul>
<li>z test from proportions - CLT-based normality approximation of the binomial distribution</li>
<li>chi-square test</li>
</ul>
<p><em>If</em> we had continous data (e.g.&nbsp;revenues for version A or B), we would just use a Student’s T test (or Welch test). For the case of equal variances, this amount to:</p>
<p><span class="math display">\[T_{dof} = \frac{ \bar{x}_A - \bar{x}_B}{\sqrt{\frac{s^2_A}{n_A} + \frac{s^2_B}{n_B}}}\]</span></p>
<p>where <span class="math inline">\(SD_{pooled} = \sqrt{\frac{s^2_A}{n_A} + \frac{s^2_B}{n_B}}\)</span> is the pooled standard deviation of the two samples.</p>
<p>In the case of proportions we refer to the binomial distribution, where the mean (expected value) is <span class="math inline">\(n \cdot p\)</span> and the variance is <span class="math inline">\(n \cdot p \cdot (1-p)\)</span>. For sufficiently large samples (e.g.&nbsp;&gt; 1000), we can approximate a binomial distribution with a gaussian having parameters:</p>
<p><span class="math display">\[\mu = p, \sigma = \sqrt{\frac{p(1-p)}{n}}\]</span> This allows us to formulate a test for the difference between the two proportions in a similar way to the t test:</p>
<p><span class="math display">\[z = \frac{p_B - p_A}{\sqrt{SE_A^2 + SE_B^2}}\]</span> where <span class="math inline">\(SE_A\)</span> is the standard error for A (and analogously for B)</p>
<p><span class="math display">\[SE_A = \sqrt{\frac{p_A(1-p_A)}{N_A}}\]</span> Finally, we compare the obtained Z with the critical value for the chosen significance level.</p>
<p>Let’s implement this:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>nconv_B <span class="ot">&lt;-</span> df<span class="sc">$</span>n_conversions[<span class="dv">1</span>]</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>nconv_A <span class="ot">&lt;-</span> df<span class="sc">$</span>n_conversions[<span class="dv">2</span>]</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>N_B <span class="ot">&lt;-</span> df<span class="sc">$</span>N_visitors[<span class="dv">1</span>]</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>N_A <span class="ot">&lt;-</span> df<span class="sc">$</span>N_visitors[<span class="dv">2</span>]</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>pA <span class="ot">=</span> nconv_A <span class="sc">/</span> N_A</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>pB <span class="ot">=</span> nconv_B <span class="sc">/</span> N_B</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>SE_B <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(pB <span class="sc">*</span> (<span class="dv">1</span><span class="sc">-</span>pB) <span class="sc">/</span> N_B)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>SE_A <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(pA <span class="sc">*</span> (<span class="dv">1</span><span class="sc">-</span>pA) <span class="sc">/</span> N_A)</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>SE_diff <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(SE_B<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> SE_A<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> (pB <span class="sc">-</span> pA)<span class="sc">/</span>SE_diff</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a><span class="co"># two-tails test</span></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>pval <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(z)) )</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(pval)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.000584267</code></pre>
</div>
</div>
<p>A quick graphical display of the comparison, together with all the elements of the calculations, can be obtained using the <a href="https://abtestguide.com/calc/">AB Testguide website</a></p>
<p><img src="imgs/abtestguide.png" class="img-fluid"></p>
<p>Alternatively, we can use the Pearson chi-square test, to test whether the two distributions - sampled in our pA and pB observations - are the same</p>
<p><span class="math display">\[\chi^2 = \sum{\frac{(O_i - E_i)^2}{E_i}}\]</span></p>
<p>In this case we can either use the <code>prop.test()</code> function, or the <code>chisq.test()</code> function.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>ABresult <span class="ot">&lt;-</span> <span class="fu">prop.test</span>(df<span class="sc">$</span>n_conversions, df<span class="sc">$</span>N_visitors, <span class="at">correct =</span> F, <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(ABresult)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    2-sample test for equality of proportions without continuity correction

data:  df$n_conversions out of df$N_visitors
X-squared = 11.823, df = 1, p-value = 0.0005851
alternative hypothesis: two.sided
95 percent confidence interval:
 0.01590500 0.05806371
sample estimates:
   prop 1    prop 2 
0.2054054 0.1684211 </code></pre>
</div>
</div>
<p>If we want to use the chi-square test function directly, we need to reshape our observation into a contingency table.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>contingency_table <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(n_conv_B, n_conv_A, N_B <span class="sc">-</span> n_conv_B, N_A <span class="sc">-</span> n_conv_A), <span class="at">ncol =</span> <span class="dv">2</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(contingency_table) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"YES_Conv"</span>, <span class="st">"No_Conv"</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(contingency_table) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"B"</span>, <span class="st">"A"</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>contingency_table <span class="ot">&lt;-</span> contingency_table <span class="sc">*</span> Ndays_runtime</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(contingency_table, <span class="at">correct =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  contingency_table
X-squared = 9.7459, df = 1, p-value = 0.001797</code></pre>
</div>
</div>
<p>The final results are of course exactly the same, and they are (as expected) comparable to those obtained using the normal approximation of the binomial distribution.</p>
<p><br></p>
</section>
<section id="insights-from-the-analysis" class="level2">
<h2 class="anchored" data-anchor-id="insights-from-the-analysis">Insights from the analysis</h2>
<p>It appears that we can be reasonably confident that implementing option B - the photo of the cafeteria as a workplace - will increase the conversion rate, and therefore our profit.</p>
<p>But there are more interesting information we can gather from our analysis:</p>
<ol type="1">
<li><p><strong>The observed conversion rate for the baseline variant (photo of cafeteria as a meeting place) matches our expectations</strong>. Of course, this happened here because we actually created the data <em>ad hoc</em>, but the point to retain is that it is important to check whether our initial expectation about the baseline is met by the observation.</p></li>
<li><p><strong>The efficacy of the new photo is smaller than expected</strong>. We were expecting to increase the conversion rate by 35-40%. As a matter of fact, the result from the experiment is that the new picture increases conversion “only” by 25% with respect to the baseline. We must therefore evaluate whether this option is still interesting for our business</p></li>
<li><p>We said that from the results we can be <em>reasonably confident</em> that implementing option B will increase our profits 25% with respect to the actual conversion rate. We can attach a quantitative meaning to this <em>confidence</em>, namely by looking at the confidence intervals for this result.</p></li>
</ol>
</section>
<section id="confidence-interval" class="level2">
<h2 class="anchored" data-anchor-id="confidence-interval">Confidence interval</h2>
<p>Confidence intervals (CI) are used to estimate the range of the true (but unknown) value of our parameter of interest from our sampling distribution, with a given confidence level (e.g.&nbsp;95%).</p>
<p><span class="math display">\[CI = [\hat p_{Diff} + z_{CL} \cdot SE_{Diff}; \hat p_{Diff} - z_{CL} \cdot SE_{Diff}; ]\]</span> Where:</p>
<ul>
<li><span class="math inline">\(\hat p_{Diff} = \hat p_B - \hat p_A\)</span>, that is the difference between the two estimates of conversion rate</li>
<li><span class="math inline">\(z_{CL}\)</span> is the probability associated with our confidence level, e.g.&nbsp;95%</li>
<li><span class="math inline">\(SE_{Diff}\)</span> is the standard error of the difference between the two proportions, as calculated above</li>
</ul>
<p>It is the range in which the difference of the conversion rates would be found if the experiment would be repeated many times.</p>
<p>The CI can be used for inference, alternatively to the null-hypothesis testing approach. Specifically, if the CI <em>includes</em> 0 (or another value that would make the difference between the two conversion rates not interesting), then we can conclude that there is no significant difference in the efficacy of A or B in terms of conversion rates.</p>
<p>In our case we can calculate the CI as follows:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># for a 95% confidence level</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">=</span> <span class="fl">0.05</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>z_CL <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="dv">1</span><span class="sc">-</span>(alpha<span class="sc">/</span><span class="dv">2</span>))</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Margin of error</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>MOE <span class="ot">&lt;-</span> z_CL <span class="sc">*</span> SE_diff</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>CI_low  <span class="ot">&lt;-</span> (pB <span class="sc">-</span> pA) <span class="sc">-</span> MOE</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>CI_high <span class="ot">&lt;-</span> (pB <span class="sc">-</span> pA) <span class="sc">+</span> MOE</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"95% CI around the difference between pB and PA: ["</span>,CI_low,CI_high,<span class="st">"]"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>95% CI around the difference between pB and PA: [ 0.015905 0.05806371 ]</code></pre>
</div>
</div>
<p>As expected, this CI does <em>not</em> contain 0, therefore we reject the null hypothesis of no difference between the two conversion rates.</p>
<p>Importantly, the CI can also be used to compare what we expect in the future - based on our experiment - with what we will actually obtain.</p>
<p>For instance, one month after we implement photo B (cafeteria as a shared workplace), we might get a 19% increase in conversion rates, rather than the expected 20.5%. While this might disappoint us, it is indeed within the range described by our confidence interval.</p>
<p>In fact, our CI around the difference in coversion rates (3.7%) ranges between 1.59% and 5.81%. This means that while our point estimate for the conversion rates is 20.54%, based on our CI we can expect is to range from 18.43% (pA + CI_low) to 22.65% (pA + CI_high).</p>
</section>
<section id="links" class="level2">
<h2 class="anchored" data-anchor-id="links">Links</h2>
<p><a href="https://www.searchdiscovery.com/blog/sample-size-calculation-myth-buster-edition/">Kelly Wortham’s Sample Size Calculation - Myth Buster Edition</a> and the associated <a href="https://www.searchdiscovery.com/how-we-help/services/optimization/sample-size-calculator/">calculator app</a></p>
<p><a href="https://abtestguide.com/calc/">AB Testguide calculator</a>. Scroll to the bottom of the page for some technical articles.</p>
<p><a href="https://blog.analytics-toolkit.com/2018/confidence-intervals-p-values-percent-change-relative-difference/">Georgiev Intervals and p-values for percent change</a></p>
<p><a href="http://mlwiki.org/index.php/Binomial_Proportion_Tests">MLwiki binomial proportion tests</a></p>
<p><a href="http://mlwiki.org/index.php/Binomial_Proportion_Confidence_Intervals">MLwiki binomial proportion confidence intervals</a></p>
<p><a href="https://www.linkedin.com/pulse/confidence-intervals-ab-testing-results-surbhi-jain/">Confidence intervals in A/B testing results</a></p>
<p><a href="https://hbr.org/2017/06/a-refresher-on-ab-testing">HBR refresher on A/B testing</a></p>
<p><a href="https://www.khanacademy.org/math/ap-statistics/xfb5d8e68:inference-categorical-proportions/two-sample-z-interval-proportions/v/confidence-intervals-for-the-difference-between-two-proportions">Khan on CI for the difference between proportions</a></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>